name: sync-fork
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
          token: ${{ secrets.PAT_PUSH_WITH_WORKFLOW }}
      - name: Sync fork
        run: |
          git remote add fork https://github.com/cccteam/github-workflows.git
          git pull fork --tags master
          git merge --ff-only fork/master
          git push origin master
          git push --tags origin
